name: my-first-flow
on:
  push:
    branches: [main]
    workflow-dispatch:
    tags:
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Hello World!"
      - uses: actions/checkout@v2
      - run: ls
        #- docker login -u vietnamese64 -pass nhomaiTLN123_
      - run: echo "goodbye"
      - shell: bash
        env:
            SUPER_SECRET: ${ secrets.DOCKERHUB_USERNAME}}
    run:
      echo "$SUPER_SECRET"
